In [37]:
import pandas as pd
import numpy as np
import os

### Get all the data we need, and change it to dataframe

In [38]:
first_clean_recipe_path='./first_clean_recipe/'
dfs=[]
for file in os.listdir(first_clean_recipe_path):
    df = pd.read_csv(os.path.join(first_clean_recipe_path,file))
    df=pd.DataFrame(df['Food_Name']).reset_index(drop=True)
    df['Juan']=file.split('.')[0].split('1_')[1]
    # print(df.shape)
    dfs.append(df)
    # display(df.head())

food_name_juan_df=pd.concat(dfs)
# print(food_name_juan_df.shape)
display(food_name_juan_df.head())

  Food_Name                     Juan
0      颇儿必汤  JuanDiYiJuZhenYiZhuan_3
1    米哈讷关列孙  JuanDiYiJuZhenYiZhuan_3
0       姜黄鱼  JuanDiYiJuZhenYiZhuan_2
1        攒雁  JuanDiYiJuZhenYiZhuan_2
2      猪头姜豉  JuanDiYiJuZhenYiZhuan_2

In [4]:
# food_name_juan_df.to_csv(f'other_data/food_name__with_juan_df.csv', index=False, encoding='utf-8-sig')

In [39]:
categorize_path='./categorize/'

categories_df = pd.read_csv(os.path.join(categorize_path, 'categories.csv'))
effect_df = pd.read_csv(os.path.join(categorize_path, 'effect.csv'))
ingredient_category_df = pd.read_csv(os.path.join(categorize_path, 'ingredient_category.csv'))
methods_df = pd.read_csv(os.path.join(categorize_path, 'methods.csv'))

display(categories_df.head())
display(effect_df.head())
display(ingredient_category_df.head())
display(methods_df.head())

  category  Food_Name
0        膏  铁 瓮先生 琼玉膏
1        煎        地仙煎
2        煎        金髓煎
3        膏       天门冬膏
4       菜品       服天门冬

   Effect Food_Name
0     治久痔       鲫鱼羹
1     治肠风       鲫鱼羹
2  治大便常有血       鲫鱼羹
3     治久痔       獭肝羹
4   治下血不止       獭肝羹

  Ingredient                    category
0         半夏  chinese_medicinal_material
1         菵草                       plant
2         藜芦                       plant
3         凡石                       other
4         皂角  chinese_medicinal_material

  method  Food_Name
0      煮  铁 瓮先生 琼玉膏
1      煮        地仙煎
2      煮        金髓煎
3      熬        金髓煎
4      熬       天门冬膏

In [40]:
translation_receipe_path='./translation_recipe_v1_utf8/'

dfs=[]
for file in os.listdir(translation_receipe_path):
    # Specify the encoding when reading the CSV file
    df = pd.read_csv(os.path.join(translation_receipe_path,file), encoding='utf-8')
    dfs.append(df)


translation_receipe_df=pd.concat(dfs).reset_index(drop=True)
display(translation_receipe_df.head())

,Food_Name,Effect,Ingredients,Steps
0,姜黄鱼,NaN,鲤鱼 十个，去皮鳞 白面 二斤 豆粉 一斤 芫荽末 二两,上述食材，用盐和料物混合拌匀，将鱼腌制后，入油中炸至熟透，再加入生姜丝、芫荽叶、胭脂染制的辣...
1,攒雁,NaN,雁 五个，煮熟，切攒 姜末 半斤,右边的食材，用优质的肉汤炒制，然后加入葱和醋，混合均匀。
2,猪头姜豉,NaN,猪头 二个，洗净，切成块 陈皮 二钱，去白 良姜 二钱 小椒 二钱 官桂 二钱 草果...,上述食材，一同炖煮，然后加入芥末炒制，再加入葱、醋和盐，调和均匀。
3,蒲黄瓜齑,NaN,净羊肉 十斤，煮熟，切如瓜齑 小椒 一两 蒲黄 半斤,上述食材，用细的调料物混合，再加入盐拌匀。
4,攒羊头,NaN,羊头 五个，煮熟攒 姜末 四两 胡椒 一两,上述食材，用优质的肉汤炒制，然后加入葱、盐和醋，混合均匀。

In [41]:
ingredient_path='./ingredient/'

files=['v1_JuanDiErShenXianFuShi.csv_ingredient.csv','v1_JuanDiErShiLiaoZhuBing.csv_ingredient.csv','v1_JuanDiErZhuBanTangJian.csv_ingredient.csv','v1_JuanDiYiJuZhenYiZhuan_1.csv_ingredient.csv', 'v1_JuanDiYiJuZhenYiZhuan_2.csv_ingredient.csv','v1_JuanDiYiJuZhenYiZhuan_3.csv_ingredient.csv']

dfs=[]

total_shape=[0,3]

for file_name in files:
    df = pd.read_csv(os.path.join(ingredient_path, file_name),encoding = "UTF-8")
    dfs.append(df)
    total_shape[0]+=df.shape[0]

ingredient_df=pd.concat(dfs).reset_index(drop=True)
print(ingredient_df.shape)
display(ingredient_df.head())

(742, 3)

  Food_Name Ingredient Amount
0       神枕法         半夏    NaN
1       神枕法         菵草    NaN
2       神枕法         藜芦    NaN
3       神枕法         凡石    NaN
4       神枕法         皂角    NaN

### Get unique: categories, effect, ingredient_category, methods

In [44]:
unique_categorize_path='./unique_categorize/'

unique_ingredient_category_df=pd.read_csv(os.path.join(unique_categorize_path,'unique_ingredient_category.csv'))
unique_categories_df=pd.read_csv(os.path.join(unique_categorize_path,'unique_categories.csv'))
unique_effect_df=pd.read_csv(os.path.join(unique_categorize_path,'unique_effect.csv'))
unique_methods_df=pd.read_csv(os.path.join(unique_categorize_path,'unique_methods.csv'))

display(unique_ingredient_category_df.head())
display(unique_categories_df.head())
display(unique_effect_df.head())
display(unique_methods_df.head())

                     category
0  chinese_medicinal_material
1                       plant
2                       other
3                       spice
4                       fruit

  category
0        膏
1        煎
2       菜品
3        羹
4        粥

   Effect
0     治久痔
1     治肠风
2  治大便常有血
3   治下血不止
4    治野鸡病

  method
0      煮
1      熬
2      蒸
3      煎
4      焙

**Dataframes we have now:**

- `food_name_juan_df`: Food_Name, Juan

- `categories_df`: category, Food_Name

- `effect_df`: Effect, Food_Name

- `ingredient_category_df`: Ingredient, category

- `methods_df`: method, Food_Name

- `translation_receipe_df`: Food_Name, Effect, Ingredients, Steps

- `ingredient_df`: Food_Name, Ingredient, Amount

- `unique_ingredient_category_df`: category

- `unique_categories_df`: category

- `unique_effect_df`: Effect

- `unique_methods_df`: method